---
name: issue-labeled
on:
  issues:
    types: [labeled]
jobs:
  asd:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.issue.body }}"
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        submodules: true
    - run: |
        ls -lha
