---
name: issue-labeled
on:
  issues:
    types: [labeled]
jobs:
  asd:
    runs-on: ubuntu-latest
    steps:
      - env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          ISSUE_BODY: |
            ${{ github.event.issue.body }}
          AWK_SCRIPT: |
            /^<!--/,/^-->/ { next             } # ignore xml-style comment blocks
                           { gsub(/[\'"]/,"") } # make sure yaml keys/values are not quoted
            $1==":branch:" { print $2; exit   } # extract the branch (if exists) and exit
        run: |
          export BRANCH=$(echo "$ISSUE_BODY" | awk "$AWK_SCRIPT")
          echo "::set-env name=BRANCH::$BRANCH"

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ env.BRANCH }}

      - run: printenv | sort

      - run: git status

      - uses: hashicorp/setup-terraform@v1

      - run: terraform version

      - run: |
          cat `which terraform`

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install json

      - run: ruby --version

      - run: |
          echo BEGIN
          terraform output -json -no-color
          echo END

      - run: ruby output.rb

      - run: echo $BRANCH
