---
name: issue-labeled
on:
  issues:
    types: [labeled]
jobs:
  asd:
    runs-on: ubuntu-latest
    env: { ACTIONS_ALLOW_UNSECURE_COMMANDS: true }
    steps:
      - run: |
          printenv | sort

      - run: |
          export BRANCH=$(echo '${{ github.event.issue.body }}' | awk '$1==":branch:"{print$2;exit}')
          echo "::set-env name=BRANCH::$BRANCH"

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ env.BRANCH }}

      - run: |
          git status
