---
name: issue-labeled
on:
  issues:
    types: [labeled]
jobs:
  asd:
    runs-on: ubuntu-latest
    steps:
      - env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          ISSUE_BODY: |
            ${{ github.event.issue.body }}
        run: |
          export BRANCH=$(echo "$ISSUE_BODY" | awk '$1==":branch:"{print$2;exit}')
          echo "::set-env name=BRANCH::$BRANCH"

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ env.BRANCH }}

      - run: git status

      - uses: hashicorp/setup-terraform@v1

      - run: terraform version

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: ruby --version

      - run: |
          echo BEGIN
          terraform output -json -no-color
          echo END

      - run: ruby output.rb
