---
name: unit-testing
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - '**'
    paths-ignore:
      - '**'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install rspec
      - run: ./tests.sh
